/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include "ARMCM3.h"
#include "system_ARMCM3.h"

#include "STM32F103x8.h"
#include "stm32f103x8_EXTI_driver.h"
#include "cmsis_armclang.h"
#include "core_cm3.h"
volatile 	int AdditionResult,MultiplicationResult,SubtractionResult;




int OS_SVC_Set(int SVC_ID,int a, int b) {

	int result;

	switch(SVC_ID)
	{
		case 0:
			__asm("svc #0x00");
			break;

		case 1:
			__asm("svc #0x01");
			break;

		case 2:
			__asm("svc #0x02");
			break;
	}
	
	
  __asm("MOV %0,R0"
 	      : "=r" (result));
			
	return result;

}

void OS_SVC(uint32_t *Stack_Frame)
{

	uint8_t SVC_Number;
	uint32_t value1,value2;
	SVC_Number = *((uint8_t *)(((uint8_t *)Stack_Frame[6]) - 2));
	value1 = Stack_Frame[1];
	value2 = Stack_Frame[2];

	switch(SVC_Number)
	{
		case 0:
			Stack_Frame[0] = value1 + value2;
			break;

		case 1:
			Stack_Frame[0] = value1 - value2;
			break;

		case 2:
			Stack_Frame[0] = value1 * value2 ;
			break;

	}


}



__attribute ((naked)) void SVC_Handler()
{

	//__asm("TST LR,#4");
	__asm("TST LR,#4 \n\t"
	      "ITE EQ \n\t" 
	      "MRSEQ R0,MSP \n\t"
				"MRSNE R0,PSP \n\t"
				"B OS_SVC");
	//__asm("LDR R0,[R0,#24]");
	//__asm("LDRB R0,[R0,#-2]");
	//__asm("BX LR");
	
}



int main(void)
{
	

	AdditionResult = OS_SVC_Set(0,5,2);
	SubtractionResult = OS_SVC_Set(1,5,2);
	MultiplicationResult = OS_SVC_Set(2,5,2);
					
	
	while (1)
	{
	}


}
