/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#include "STM32F103x8.h"
#include "stm32f103x8_EXTI_driver.h"

/* ========================================================
                    Macros to Switch access level
	========================================================= */
	
	/* Read Data from CONTROL register and or with 0x1 and
	write data to register */

#define ACCESS_LEVEL_UNPRIVILEGE() \
        __asm("MRS R0,CONTROL");   \
				__asm("ORR R0,R0,#0x01");  \
				__asm("MSR CONTROL,R0");   
				
#define ACCESS_LEVEL_PRIVILEGE()	 \
        __asm("MRS R0,CONTROL");   \
        __asm("LSR R0,R0,#0x01");  \
				__asm("LSL R0,R0,#0x01");  \
				__asm("MSR CONTROL,R0");

 uint8_t IRQ_Flag = 0;
 uint32_t CONTROL_Regitser_Value;
 volatile uint32_t PSR_Register_value;
 

void EXTI9_CALLBACK(void)
{
	IRQ_Flag = 1;
	ACCESS_LEVEL_PRIVILEGE();
	
}

int main(void)
{
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

	//Set EXTI Configuration
	EXTI_PinConfig_t EXTIConfig;
	EXTIConfig.EXTI_PIN = EXTI9PB9;
	EXTIConfig.Trigger_Case = EXTI_Trigger_RISING;
	EXTIConfig.P_IRQ_CallBack = EXTI9_CALLBACK;
	EXTIConfig.IRQ_EN = EXTI_IRQ_Enable;
	MCAL_EXTI_GPIO_Init(&EXTIConfig);



	IRQ_Flag = 1;

  
	__asm("nop \t\n nop \t\n nop");		
	
	ACCESS_LEVEL_UNPRIVILEGE();
	
	
	while (1)
	{
	  if(IRQ_Flag)
		{
			IRQ_Flag = 0;
		}
		else { /* Misra */ }
	}


}
